# source: _pages
include: [_pages]
destination: docs
# baseurl: "Healthy-Foods"
baseurl: ""
url: ""

# Build settings
markdown: kramdown

collections_dir: collections

collections:
    recipes:
        class: recipes
        output: true
        permalink: /recipes/:title
    posts:
        class: posts
        output: true
        permalink: /posts/:title

sass:
    sass_dir: _sass
